const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'https://horses2002.com','access-control-allow-credentials':'true','access-control-allow-headers':'content-type',...headers}});
const now=()=>Math.floor(Date.now()/1000);
function cors(){return new Response(null,{status:204,headers:{'access-control-allow-origin':'https://horses2002.com','access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}})}
async function secret(env,name){const value=env[name];return value&&typeof value.get==='function'?await value.get():value}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64u(a){return btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sign(payload,secretValue){const h=b64u(new TextEncoder().encode(JSON.stringify({alg:'HS256',typ:'JWT'})));const p=b64u(new TextEncoder().encode(JSON.stringify(payload)));const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secretValue),{name:'HMAC',hash:'SHA-256'},false,['sign']);const s=b64u(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(h+'.'+p)));return h+'.'+p+'.'+s}
async function verify(token,secretValue){try{const [h,p,s]=token.split('.');const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secretValue),{name:'HMAC',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',k,Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),new TextEncoder().encode(h+'.'+p));if(!ok)return null;const x=JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/')));return x.exp>now()?x:null}catch{return null}}
function maskPhone(p){return p&&p.length>6?p.slice(0,4)+'••••'+p.slice(-2):'الهاتف المسجل'}
async function sms(env,to){const sid=await secret(env,'TWILIO_VERIFY_SERVICE_SID');const account=await secret(env,'TWILIO_ACCOUNT_SID');const token=await secret(env,'TWILIO_AUTH_TOKEN');if(!sid||!account||!token)throw new Error('OTP provider configuration missing');const u='https://verify.twilio.com/v2/Services/'+encodeURIComponent(sid)+'/Verifications';const body=new URLSearchParams({To:to,Channel:'sms'});const auth=btoa(account+':'+token);const r=await fetch(u,{method:'POST',headers:{authorization:'Basic '+auth,'content-type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('OTP provider failed')}
async function checkRate(env,hash){const row=await env.DB.prepare('SELECT COUNT(*) c FROM otp_attempts WHERE national_id_hash=? AND requested_at>?').bind(hash,now()-600).first();return Number(row?.c||0)<3}
async function me(env,request){const c=request.headers.get('cookie')||'';const m=c.match(/abraj_session=([^;]+)/);if(!m)return null;const sessionSecret=await secret(env,'SESSION_SECRET');if(!sessionSecret)return null;return await verify(m[1],sessionSecret)}
export default{async fetch(request,env){if(request.method==='OPTIONS')return cors();const url=new URL(request.url);try{
if(url.pathname==='/health')return json({ok:true,service:'abraj-employee-api'});
if(url.pathname==='/auth/request-otp'&&request.method==='POST'){const {nationalId}=await request.json();const nid=String(nationalId||'').replace(/\D/g,'');if(!/^\d{8,20}$/.test(nid))return json({error:'رقم وطني غير صالح'},400);const h=await sha256(nid);if(!(await checkRate(env,h)))return json({error:'تم تجاوز عدد المحاولات. حاول بعد 10 دقائق.'},429);const e=await env.DB.prepare('SELECT id,phone_e164,status FROM employees WHERE national_id=? LIMIT 1').bind(nid).first();if(!e||e.status!=='active')return json({error:'تعذر التحقق من البيانات المدخلة.'},404);await sms(env,e.phone_e164);await env.DB.prepare('INSERT INTO otp_attempts(employee_id,national_id_hash,requested_at,ip_hash) VALUES(?,?,?,?)').bind(e.id,h,now(),await sha256(request.headers.get('CF-Connecting-IP')||'unknown')).run();return json({ok:true,maskedPhone:maskPhone(e.phone_e164)});}
if(url.pathname==='/auth/verify-otp'&&request.method==='POST'){const {nationalId,otp}=await request.json();const nid=String(nationalId||'').replace(/\D/g,'');const code=String(otp||'').replace(/\D/g,'');if(!/^\d{8,20}$/.test(nid)||!/^[0-9]{6}$/.test(code))return json({error:'بيانات التحقق غير صحيحة.'},400);const e=await env.DB.prepare('SELECT id,status,phone_e164 FROM employees WHERE national_id=? LIMIT 1').bind(nid).first();if(!e||e.status!=='active')return json({error:'تعذر التحقق من البيانات.'},401);const sid=await secret(env,'TWILIO_VERIFY_SERVICE_SID');const account=await secret(env,'TWILIO_ACCOUNT_SID');const token=await secret(env,'TWILIO_AUTH_TOKEN');if(!sid||!account||!token)return json({error:'خدمة التحقق غير مهيأة.'},503);const u='https://verify.twilio.com/v2/Services/'+encodeURIComponent(sid)+'/VerificationCheck';const body=new URLSearchParams({To:e.phone_e164,Code:code});const auth=btoa(account+':'+token);const r=await fetch(u,{method:'POST',headers:{authorization:'Basic '+auth,'content-type':'application/x-www-form-urlencoded'},body});const v=await r.json();if(!r.ok||v.status!=='approved')return json({error:'رمز التحقق غير صحيح أو منتهي.'},401);const sessionSecret=await secret(env,'SESSION_SECRET');if(!sessionSecret)return json({error:'إعداد الجلسة غير مكتمل.'},503);const sessionToken=await sign({sub:e.id,exp:now()+1800},sessionSecret);await env.DB.prepare('UPDATE otp_attempts SET verified_at=? WHERE employee_id=? AND verified_at IS NULL AND requested_at>?').bind(now(),e.id,now()-900).run();return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'https://horses2002.com','access-control-allow-credentials':'true','set-cookie':'abraj_session='+sessionToken+'; Path=/; Max-Age=1800; Secure; HttpOnly; SameSite=Lax'}});}
if(url.pathname==='/auth/logout'&&request.method==='POST')return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'https://horses2002.com','access-control-allow-credentials':'true','set-cookie':'abraj_session=; Path=/; Max-Age=0; Secure; HttpOnly; SameSite=Lax'}});
if(url.pathname==='/me'&&request.method==='GET'){const s=await me(env,request);if(!s)return json({error:'جلسة الدخول غير صالحة أو منتهية.'},401);const e=await env.DB.prepare('SELECT id,employee_number,full_name,department,job_title FROM employees WHERE id=? AND status="active"').bind(s.sub).first();if(!e)return json({error:'الموظف غير موجود.'},404);const salary=await env.DB.prepare('SELECT month,basic_salary,allowances,deductions,net_salary,pdf_url FROM salaries WHERE employee_id=? ORDER BY month DESC LIMIT 1').bind(e.id).first();const attendance=await env.DB.prepare('SELECT work_date date,check_in checkIn,check_out checkOut,status FROM attendance WHERE employee_id=? ORDER BY work_date DESC LIMIT 31').bind(e.id).all();return json({employee:{employeeNumber:e.employee_number,fullName:e.full_name,department:e.department,jobTitle:e.job_title},salary:salary?{month:salary.month,basicSalary:salary.basic_salary,allowances:salary.allowances,deductions:salary.deductions,netSalary:salary.net_salary,pdfUrl:salary.pdf_url}:null,attendance:attendance.results||[]});}
return json({error:'Not found'},404);
}catch(err){console.error(err);return json({error:'حدث خطأ داخلي. حاول لاحقًا.'},500)}}};
